name: margipose
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7.4
  - cudatoolkit=10.0
  - "pytorch=1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0"
  - torchvision=0.5.0
  - x264=20131218  # The ffmpeg 3.4 conda package does not pin this dependency correctly.
  - ffmpeg=3.4
  - graphviz=2.40.1
